In [ ]:
Write a Python program to convert a list of numeric value into a one-dimensional NumPy array.

In [79]:
import numpy as np
list1=[1,2,2,4,56,7,74,9]
a=np.array([list1])
print("the a one-dimensional NumPy array is",a )
print(type(a))


the a one-dimensional NumPy array is [[ 1  2  2  4 56  7 74  9]]
<class 'numpy.ndarray'>


In [ ]:
Create a 3x3 matrix with values ranging from 2 to 10.

In [10]:
a=np.arange(2,11).reshape(3,3)
print("the 3x3 matrix with values ranging from 2 to 10 is:\n",a)

the 3x3 matrix with values ranging from 2 to 10 is:
 [[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


In [ ]:
Write a Python program to create a null vector of size 10 and update sixth value to 11

In [ ]:
a = np.zeros(10)
print(a)
print("changing sixth value to 11")
x[6] = 11
print(a)

In [ ]:
Write a Python program to create a array with values ranging from 12 to 38.

In [16]:
a=np.arange(12,39)
print(a)

[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36
 37 38]


In [ ]:
Write a Python program to reverse an array (first element becomes last)

In [46]:
a=np.arange(8).reshape(2,4)
print(a)
print("the reverse array \n",np.flipud(np.fliplr(a)))


[[0 1 2 3]
 [4 5 6 7]]
the reverse array 
 [[7 6 5 4]
 [3 2 1 0]]


 Write a Python program to an int array converted to a float type.

In [32]:
a=np.arange(8).reshape(2,4)
print("the current array type is",a.dtype)
a=a.astype(float)
print("the array type is",a.dtype)

int32
float64


In [ ]:
Write a Python program to create a 2d array (5x5) with 1 on the border and 0 inside.

In [110]:
a=np.ones(25).reshape(5,5)
a[1:4,1:4]=a[1:4,1:4]*0
print("2d array (5x5) with 1 on the border and 0 inside\n",a)

2d array (5x5) with 1 on the border and 0 inside
 [[ 1.  1.  1.  1.  1.]
 [ 1.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  1.]
 [ 1.  1.  1.  1.  1.]]


In [ ]:
Write a Python program to find the number of elements of an array
, length of one array element in bytes and total bytes consumed by the elements.

In [54]:
a=np.arange(8).reshape(2,4)
print( "the number of elements in the array is",a.size)
print("length of one array element in bytes is", a.itemsize)
print("total bytes consumed by the elements is",a.size*a.itemsize)

the number of elements in the array is 8
length of one array element in bytes is 4
total bytes consumed by the elements is 32


In [ ]:
Write a Python program to create a function cube which cubes all the elements of an array.

In [31]:
import numpy as np
def cube(a):
    it = np.nditer([a, None])
    for i, j in it:
        j[...] = i*i*i
    return it.operands[1]
print(cube([1,2,3]))

[ 1  8 27]


In [ ]:
Write a Python program to how to add an extra column to an numpy array.

In [66]:
a=np.arange(8).reshape(2,4)

b=np.insert(a,4,[1,2],axis=1)
print(" the array with extra column is\n",b)

 the array with extra column is
 [[0 1 2 3 1]
 [4 5 6 7 2]]


In [ ]:
Write a Python program to remove the negative values in a numpy array with 0.


In [74]:
a=np.array([[1,2],[-1,8],[9,-6]])
bool_array = (a<0)
print("array:\n",a)
a[bool_array]=a[bool_array]*0
print("the array without negative values\n",a)

array:
 [[ 1  2]
 [-1  8]
 [ 9 -6]]
the array without negative values
 [[1 2]
 [0 8]
 [9 0]]


In [ ]:
Create a  one dimensional array with 3 elements. Extend the array by repeating the current elements, 3 times.

In [3]:
import numpy as np
a=np.arange(3)
a=np.hstack([a,a,a])
print("the array by repeating the current elements, 3 times",a)

the array by repeating the current elements, 3 times [0 1 2 0 1 2 0 1 2]


In [ ]:
Write a Python program compare two arrays using numpy

In [97]:
a=np.arange(3)
b=np.zeros(3)
c=np.arange(3)
print(" is array1 equals array2:",np.array_equal(a,c))

array1 equals array2: True


In [ ]:
Write a Python program to find the memory size of a NumPy array

In [123]:
a=np.arange(8).reshape(2,4)
print("the memory size",a.nbytes)

the memory size 32


In [ ]:
Create a 3x5 array with random elements. Reshape this into 5x3

In [94]:
a=np.array([[1,2,3,4,5],[6,7,8,9,0],[11,12,13,14,15]])
print("the 3x5 array:\n",a)
print("the 5x3 array is\n",a.reshape(5,3))

the 3x5 array:
 [[ 1  2  3  4  5]
 [ 6  7  8  9  0]
 [11 12 13 14 15]]
the 5x3 array is
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [ 0 11 12]
 [13 14 15]]


In [ ]:
Write a Python program to create a 2d array (5x5) with 1 on the border and 0 inside

In [4]:
import numpy as np
a= np.eye(6)
b=np.array([a]*6)
print("2d array (5x5) with 1 on the border and 0 inside\n",b)

2d array (5x5) with 1 on the border and 0 inside
 [[[ 1.  0.  0.  0.  0.  0.]
  [ 0.  1.  0.  0.  0.  0.]
  [ 0.  0.  1.  0.  0.  0.]
  [ 0.  0.  0.  1.  0.  0.]
  [ 0.  0.  0.  0.  1.  0.]
  [ 0.  0.  0.  0.  0.  1.]]

 [[ 1.  0.  0.  0.  0.  0.]
  [ 0.  1.  0.  0.  0.  0.]
  [ 0.  0.  1.  0.  0.  0.]
  [ 0.  0.  0.  1.  0.  0.]
  [ 0.  0.  0.  0.  1.  0.]
  [ 0.  0.  0.  0.  0.  1.]]

 [[ 1.  0.  0.  0.  0.  0.]
  [ 0.  1.  0.  0.  0.  0.]
  [ 0.  0.  1.  0.  0.  0.]
  [ 0.  0.  0.  1.  0.  0.]
  [ 0.  0.  0.  0.  1.  0.]
  [ 0.  0.  0.  0.  0.  1.]]

 [[ 1.  0.  0.  0.  0.  0.]
  [ 0.  1.  0.  0.  0.  0.]
  [ 0.  0.  1.  0.  0.  0.]
  [ 0.  0.  0.  1.  0.  0.]
  [ 0.  0.  0.  0.  1.  0.]
  [ 0.  0.  0.  0.  0.  1.]]

 [[ 1.  0.  0.  0.  0.  0.]
  [ 0.  1.  0.  0.  0.  0.]
  [ 0.  0.  1.  0.  0.  0.]
  [ 0.  0.  0.  1.  0.  0.]
  [ 0.  0.  0.  0.  1.  0.]
  [ 0.  0.  0.  0.  0.  1.]]

 [[ 1.  0.  0.  0.  0.  0.]
  [ 0.  1.  0.  0.  0.  0.]
  [ 0.  0.  1.  0.  0.  0.]
  [ 0.  0.  0.  

In [ ]:
17. The following table includes marks of students in various subjects.
Each row corresponds to a student [ Rajesh, Rima, Ram and Joseph]  
coulmn correspond to a subject [Maths, Physics, Chemistry, Sociology]

15 . 20 .   25  12
45 .  50 .  50 . 48
8 .    7 .   3 .    2
28 .  32 . 40 .  39

Do the following 
A.
1. FInd the mean, median, mode and standard deviation for marks of each subject
2. What is the minimum and maximum of each subject?
3. Print the subject in  each student good at and poor at ?
4. What is the overall class mean, mode, median and standard deviation

B.Teacher just announced the marks of English. They are 40, 49, 10 and 35 for eah student.
Re-calculate all subparts of A.
C. A new student joined the class. For the time being, the scores are going to be zero for each subject. 
Re-calculate A again with the new student.
D. Print the current score card for the class

In [59]:
import numpy as np
a=np.array([[15,20,25,12],[45,50,50,48],[8,7,3,2],[28,32,40,39]])
students=["Rajesh","Rima","Ram","Joseph"] 
subjects=["Maths","Physics","Chemistry","Sociology"]
def A():
    mean =a.mean(axis=0)
    print("the means of the subjects are as follows:")
    for i,subject in enumerate(subjects):
        print(subject,":",mean[i])
    
    median=np.median(a,axis=0)
    print("the median of the subjects are as follows:")
    for i,subject in enumerate(subjects):
        print(subject,":",median[i])
    
    from scipy import stats
    mode=stats.mode(a,axis=0)
    mode=mode[1]
    print(mode)
    print("the mode of the subjects are as follows:")
    for i,subject in enumerate(subjects):
        print(subject,":",mode[0][i])
    
    sd=np.std(a,axis=0)
    print("the standard deviation of the subjects are as follows:")
    for i,subject in enumerate(subjects):
        print(subject,":",sd[i])

    max=np.max(a,axis=0)
    print("the maximum marks in the respective subjects are as follows ")
    for i,subject in enumerate(subjects):
        print(subject,":",max[i])

    min=np.min(a,axis=0)
    print("the maximum marks in the respective subjects are as follows ")
    for i,subject in enumerate(subjects):
        print(subject,":",min[i])
        
    min_s=np.min(a,axis=1)
    max_s=np.max(a,axis=1)
    for i,student in enumerate(students):
        print(student,"is good at",subjects[a[i].argmax()],"and poor at",subjects[a[i].argmin()])

    print("the overall class mean :", np.mean(a))
    print("the overall class median :", np.median(a))
    mode=stats.mode(a)
    print("the overall class mode:",mode[1])

A()




the means of the subjects are as follows:
Maths : 24.0
Physics : 27.25
Chemistry : 29.5
Sociology : 25.25
the median of the subjects are as follows:
Maths : 21.5
Physics : 26.0
Chemistry : 32.5
Sociology : 25.5
[[1 1 1 1]]
the mode of the subjects are as follows:
Maths : 1
Physics : 1
Chemistry : 1
Sociology : 1
the standard deviation of the subjects are as follows:
Maths : 14.0890028036
Physics : 15.8331140336
Chemistry : 17.6988700204
Sociology : 18.8596792125
the maximum marks in the respective subjects are as follows 
Maths : 45
Physics : 50
Chemistry : 50
Sociology : 48
the maximum marks in the respective subjects are as follows 
Maths : 8
Physics : 7
Chemistry : 3
Sociology : 2
Rajesh is good at Chemistry and poor at Sociology
Rima is good at Physics and poor at Maths
Ram is good at Maths and poor at Sociology
Joseph is good at Chemistry and poor at Maths
the overall class mean : 26.5
the overall class median : 26.5
the overall class mode: [[1 1 1 1]]


In [45]:
subjects.append("english")
marks=np.array([40, 49, 10,35]).reshape(4,1)
a=np.append(a,marks,axis=1)
A()

the means of the subjects are as follows:
Maths : 24.0
Physics : 27.25
Chemistry : 29.5
Sociology : 25.25
english : 33.5
the median of the subjects are as follows:
Maths : 21.5
Physics : 26.0
Chemistry : 32.5
Sociology : 25.5
english : 37.5
[[1 1 1 1 1]]
the mode of the subjects are as follows:
Maths : 1
Physics : 1
Chemistry : 1
Sociology : 1
english : 1
the standard deviation of the subjects are as follows:
Maths : 14.0890028036
Physics : 15.8331140336
Chemistry : 17.6988700204
Sociology : 18.8596792125
english : 14.4654761415
the maximum marks in the respective subjects are as follows 
Maths : 45
Physics : 50
Chemistry : 50
Sociology : 48
english : 49
the maximum marks in the respective subjects are as follows 
Maths : 8
Physics : 7
Chemistry : 3
Sociology : 2
english : 10
the overall class mean : 27.9
the overall class median : 30.0
the overall class mode: [[1 1 1 1 1]]


In [46]:
students.append("b")
marks_s=np.zeros(5).reshape(1,5)
a= np.append(a,marks_s,axis=0)
A()

the means of the subjects are as follows:
Maths : 19.2
Physics : 21.8
Chemistry : 23.6
Sociology : 20.2
english : 26.8
the median of the subjects are as follows:
Maths : 15.0
Physics : 20.0
Chemistry : 25.0
Sociology : 12.0
english : 35.0
[[1 1 1 1 1]]
the mode of the subjects are as follows:
Maths : 1
Physics : 1
Chemistry : 1
Sociology : 1
english : 1
the standard deviation of the subjects are as follows:
Maths : 15.8417170787
Physics : 17.870646323
Chemistry : 19.7443662851
Sociology : 19.6611291639
english : 18.626862323
the maximum marks in the respective subjects are as follows 
Maths : 45.0
Physics : 50.0
Chemistry : 50.0
Sociology : 48.0
english : 49.0
the maximum marks in the respective subjects are as follows 
Maths : 0.0
Physics : 0.0
Chemistry : 0.0
Sociology : 0.0
english : 0.0
the overall class mean : 22.32
the overall class median : 20.0
the overall class mode: [[1 1 1 1 1]]


In [62]:
print("the markssheet of the class")
for i,student in enumerate(students):
    print(student,"")
    for j,subject in enumerate(subjects):
        print(subject,":",a[i][j])
    print("\n")

    
            

the markssheet of the class
Rajesh 
Maths : 15
Physics : 20
Chemistry : 25
Sociology : 12


Rima 
Maths : 45
Physics : 50
Chemistry : 50
Sociology : 48


Ram 
Maths : 8
Physics : 7
Chemistry : 3
Sociology : 2


Joseph 
Maths : 28
Physics : 32
Chemistry : 40
Sociology : 39


