 Create a vector or array of 100 elements. Its 50th value should be    50.0 and other values should be 0.0

In [5]:
import numpy as np
a=np.zeros(100)
a[49]=50
print(a)

[  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
   0.   0.   0.   0.  50.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.]


Create a vector or array of 100 elements. Its 50th value should be    10.0 and other values should be 1.0

In [6]:
b=np.ones(100)
b[49]=10
print(b)

[  1.   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.
   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.
   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.
   1.   1.   1.   1.  10.   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.
   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.
   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.
   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.]


 Create a  vector or array whose values are from 3, 30 (1 mark)

In [8]:
arr=np.arange(3,31)
print(arr)

[ 3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27
 28 29 30]


 X = (1,2,3,4,5).  Reverse and print X (1 mark)

In [18]:
X = (1,2,3,4,5)
x=np.array(X)
X=np.flip(x,axis=0)
print(X)

[5 4 3 2 1]


Create a 5x 5 matrix and values should be from 0 to 24 (1 mark)

In [20]:
a=np.arange(25).reshape(5,5)
print(a)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


Consider the following  matrix A1 and A2   (9 marks)
       A1 :
             1        3       0

             2        1        1

             3        4         0

       A2 :
             3        4         6
   
             2        1          3

             1        2          8
	a) Find min. max of the values for A1 and A2
	b) Find the mean value for A1 and A2
	c) Make the values below the diagonal as 0.0 for A1
	d) Multiply A1 and A2
	e) What are the common values between A1 and A2
	f) Swap first and 3rd rows of A1
	g) What is the  mosft frequent numbers from A1 and A2
	h) Add a column to A1 with values 1 1 1 
	i) Add a row to A2 with 2 2 2


In [92]:
a1=np.array([[1,3,0],[2,1,1],[3,4,0]])
a2=np.array([[3,4,6],[2,1,3],[1,2,8]])
print("the min value for A1 is ",a1.min())
print("the max value for A1 is ",a1.max())
print("the min value for A2 is ",a2.min())
print("the max value for A2 is ",a2.max())


the min value for A1 is  0
the max value for A1 is  4
the min value for A2 is  1
the max value for A2 is  8


In [84]:
print("the mean of A1 is",np.mean(a1))
print("the mean of A2 is",np.mean(a2))

the mean of A1 is 1.66666666667
the mean of A2 is 3.33333333333


In [85]:
l=np.triu(a1,0)
print(l)

[[1 3 0]
 [0 1 1]
 [0 0 0]]


In [86]:
mul=np.dot(a1,a2)
print(mul)

[[ 9  7 15]
 [ 9 11 23]
 [17 16 30]]


In [87]:
c=np.intersect1d(a1,a2)
print(c)

[1 2 3 4]


In [88]:
a1[0],a1[2]=a1[2].copy(),a1[0].copy()
print(a1)

[[3 4 0]
 [2 1 1]
 [1 3 0]]


In [133]:
#What is the  mosft frequent numbers from A1 and
#np.bincount(a1.flatten())
from scipy import stats
a=scipy.stats.itemfreq(a1)
print(a)
max=a[:,1].max()


[[0 2]
 [1 3]
 [2 1]
 [3 2]
 [4 1]]


In [80]:
n=np.ones(3).reshape(3,1)
col=np.hstack((a1,n))
print(col)

[[ 1.]
 [ 1.]
 [ 1.]]
[[ 3.  4.  0.  1.]
 [ 2.  1.  1.  1.]
 [ 1.  3.  0.  1.]]


In [81]:
n=np.ones(3)
row=np.vstack((a1,n))
print(row)

[[ 3.  4.  0.]
 [ 2.  1.  1.]
 [ 1.  3.  0.]
 [ 1.  1.  1.]]


In [89]:
#Write a function for matrix multiplications and additions. Use A1 and A2 to test.[3 marks]
def mul(A,B):
    result=[[0,0,0],[0,0,0],[0,0,0]]
    for i in range(len(A)):  
        for j in range(len(B[0])): 
            for k in range(len(B)): 
                result[i][j]=A[i][k] * B[k][j] 
    for r in result: 
        print(r) 
def add(A,B):
    result=[[0,0,0],[0,0,0],[0,0,0]]
    for i in range(len(A)):  
        for j in range(len(B)):
            result[i][j]=A[i]+B[j]
    for r in result: 
        print(r) 

a1=[[1,3,0],[2,1,1],[3,4,0]]
a2=[[3,4,6],[2,1,3],[1,2,8]]
mul(a1,a2)
        
        
            

[0, 0, 0]
[1, 2, 8]
[0, 0, 0]


Write a bubble sort program with normal Python  for 10 floating point numbers [3

In [119]:
def bubbleSort(a): 
    n = len(a) 
    for i in range(n):  
        for j in range(0, n-i-1):  
            if a[j] > a[j+1] : 
                a[j] = a[j+1]
                a[j+1]=a[j]
    for e in a:
        print(e, end=" ")
array=[4,8,4,7,2,6,8,1,9,5]
bubbleSort(array)

AttributeError: 'int' object has no attribute 'copy'